<?php

namespace Proxies\__CG__\Prueba\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lugar extends \Prueba\MainBundle\Entity\Lugar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'id', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'fecha', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'hora', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'lat', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'lon', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'tiempo', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'pais', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'region', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'poblacion');
        }

        return array('__isInitialized__', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'id', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'fecha', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'hora', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'lat', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'lon', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'tiempo', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'pais', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'region', '' . "\0" . 'Prueba\\MainBundle\\Entity\\Lugar' . "\0" . 'poblacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lugar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setHora($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', array($hora));

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', array());

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setLat($lat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', array($lat));

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', array());

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLon($lon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLon', array($lon));

        return parent::setLon($lon);
    }

    /**
     * {@inheritDoc}
     */
    public function getLon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLon', array());

        return parent::getLon();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempo($tiempo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempo', array($tiempo));

        return parent::setTiempo($tiempo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempo', array());

        return parent::getTiempo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', array($pais));

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', array());

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacion($poblacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacion', array($poblacion));

        return parent::setPoblacion($poblacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacion', array());

        return parent::getPoblacion();
    }

}
